-- Users schema

-- !Ups

CREATE TABLE User_AUTH.USER_DETAILS (
  `USER_ID` BINARY(16) NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `USERNAME` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(45) NULL,
  PRIMARY KEY (`USER_ID`));

-- !Downs

DROP TABLE USER_DETAILS;